## 1. Import Libraries and Reduce the dataset

In [ ]:
import pandas as pd
import numpy as np

# load only part of the dataset
df = pd.read_csv("US_Accidents_March23.csv", nrows=80000)

# save the smaller dataset
df.to_csv("raw_dataset.csv", index=False)

Pandas is used to load and manipulate datasets, while NumPy helps with numerical operations.

## 2. Load the Dtaset

In [29]:


# Load the raw dataset from the data folder
df = pd.read_csv("raw_dataset.csv")

# Display the first 5 rows
df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

This next step loads the dataset and allows us to preview the first few rows to understand its structure.

## 3. Explore the Dtaset Structure

In [9]:

# Check the dataset structure
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 46 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     80000 non-null  str
 1   Source                 80000 non-null  str
 2   Severity               80000 non-null  int64
 3   Start_Time             80000 non-null  str
 4   End_Time               80000 non-null  str
 5   Start_Lat              80000 non-null  float64
 6   Start_Lng              80000 non-null  float64
 7   End_Lat                0 non-null      float64
 8   End_Lng                0 non-null      float64
 9   Distance(mi)           80000 non-null  float64
 10  Description            80000 non-null  str
 11  Street                 80000 non-null  str
 12  City                   80000 non-null  str
 13  County                 80000 non-null  str
 14  State                  80000 non-null  str
 15  Zipcode                79993 non-null  str
 16  Country                80000 non-null  str
 17  Timezone               79993 non-null  str
 18  Airport_Code           79993 non-null  str
 19  Weather_Timestamp      79232 non-null  str
 20  Temperature(F)         78800 non-null  float64
 21  Wind_Chill(F)          3732 non-null   float64
 22  Humidity(%)            78541 non-null  float64
 23  Pressure(in)           79106 non-null  float64
 24  Visibility(mi)         78514 non-null  float64
 25  Wind_Direction         79231 non-null  str
 26  Wind_Speed(mph)        60926 non-null  float64
 27  Precipitation(in)      6614 non-null   float64
 28  Weather_Condition      78755 non-null  str
 29  Amenity                80000 non-null  bool
 30  Bump                   80000 non-null  bool
 31  Crossing               80000 non-null  bool
 32  Give_Way               80000 non-null  bool
 33  Junction               80000 non-null  bool
 34  No_Exit                80000 non-null  bool
 35  Railway                80000 non-null  bool
 36  Roundabout             80000 non-null  bool
 37  Station                80000 non-null  bool
 38  Stop                   80000 non-null  bool
 39  Traffic_Calming        80000 non-null  bool
 40  Traffic_Signal         80000 non-null  bool
 41  Turning_Loop           80000 non-null  bool
 42  Sunrise_Sunset         80000 non-null  str
 43  Civil_Twilight         80000 non-null  str
 44  Nautical_Twilight      80000 non-null  str
 45  Astronomical_Twilight  80000 non-null  str
dtypes: bool(13), float64(12), int64(1), str(20)
memory usage: 21.1 MB

This shows the column names, number of rows and  data types

## 4. Summary statistics

In [10]:
# Display summary statistics of numerical columns
df.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,80000.000000,80000.000000,80000.000000,0.0,0.0,80000.000000,78800.000000,3732.000000,78541.000000,79106.000000,78514.000000,60926.000000,6614.000000
mean,2.436825,36.070916,-119.674638,NaN,NaN,0.013688,65.038353,44.828376,60.641334,29.976226,9.299874,8.206413,0.028352
std,0.498786,2.122694,4.011331,NaN,NaN,0.293014,12.927136,17.875501,23.516537,0.265131,1.981390,4.482503,0.053759
min,1.000000,32.542587,-123.813927,NaN,NaN,0.000000,3.200000,-8.400000,4.000000,2.990000,0.100000,0.000000,0.000000
25%,2.000000,34.018642,-121.947823,NaN,NaN,0.000000,55.900000,35.800000,43.000000,29.900000,10.000000,4.600000,0.000000
50%,2.000000,37.250446,-121.071198,NaN,NaN,0.010000,64.000000,41.200000,63.000000,29.980000,10.000000,6.900000,0.010000
75%,3.000000,37.932495,-118.071495,NaN,NaN,0.010000,73.400000,50.000000,80.000000,30.070000,10.000000,10.400000,0.030000
max,4.000000,41.428753,-81.550728,NaN,NaN,51.130000,113.000000,107.000000,100.000000,33.040000,80.000000,241.700000,0.550000

This helps us understand the summary distribution of numeric variables such as temperature, humidity and visibility

## Check for Missing Values

In [11]:
# Count missing values in each column
df.isnull().sum()

ID                           0
Source                       0
Severity                     0
Start_Time                   0
End_Time                     0
Start_Lat                    0
Start_Lng                    0
End_Lat                  80000
End_Lng                  80000
Distance(mi)                 0
Description                  0
Street                       0
City                         0
County                       0
State                        0
Zipcode                      7
Country                      0
Timezone                     7
Airport_Code                 7
Weather_Timestamp          768
Temperature(F)            1200
Wind_Chill(F)            76268
Humidity(%)               1459
Pressure(in)               894
Visibility(mi)            1486
Wind_Direction             769
Wind_Speed(mph)          19074
Precipitation(in)        73386
Weather_Condition         1245
Amenity                      0
Bump                         0
Crossing                     0
Give_Way                     0
Junction                     0
No_Exit                      0
Railway                      0
Roundabout                   0
Station                      0
Stop                         0
Traffic_Calming              0
Traffic_Signal               0
Turning_Loop                 0
Sunrise_Sunset               0
Civil_Twilight               0
Nautical_Twilight            0
Astronomical_Twilight        0
dtype: int64

here we identify the missing values in each column

## 6. Remove the duplicates

In [13]:
# Check for duplicate rows
df.duplicated().sum()

# Remove duplicates
df = df.drop_duplicates()

Duplicate rows can distort the results of analysis, so they must be removed.

## 7. convert Date column

In [33]:
#Convert date column
df['Start_Time'] = pd.to_datetime(df['Start_Time'])

This allows us to perform time-based analysis such as extracting year, month, and hour.

## 8. Create useful time columns

In [34]:
# Extract useful time features
df['Year'] = df['Start_Time'].dt.year
df['Month'] = df['Start_Time'].dt.month
df['Hour'] = df['Start_Time'].dt.hour

These columns help analyze accident trends by year, month, and hour of the day.

## 9. Verify the Cleaned Dataset

In [35]:
df.shape
print(df.shape)

(80000, 49)

## 10. Save the Cleaned Dataset

In [36]:
# Save the cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)